version: '3.8'

services:
  postgres:
    container_name: ecommerce_db
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: ecommerce_postgres_data